### ISSUE TITLE
请问有baseURL的功能么

### ISSUE THREAD

**Issue by huqiliang** [fex-team/node-ral#3]
由于测试接口与实际接口URL不是完全一致 上线需要修改多个请求path 请问ral有baseURL功能么？

**Comment by hefangshi** [comment]
只是域名不一样还是说URL完全不一样？

**Comment by huqiliang** [comment]
域名不一样改下host也快的 URL内不完全一样 
测试地址: host/mock/9/api/xxx 生产地址:host2/api/xxx 
后面是一致的

**Comment by hefangshi** [comment]
不太倾向加这样的配置，建议自己封装一下ral吧，其实挺简单的，写一个函数包裹一下ral的函数，在内部处理开发环境和生产环境即可。

**Comment by huqiliang** [comment]
恩 好的
