### ISSUE TITLE
动态加载配置

### ISSUE THREAD

**Issue by gebilaoxiong** [fex-team/node-ral#36]
你好:

我希望能动态的注册服务，而不是从配置文件中加载他们;

所以我在初始化的时候配置了一个空目录:

``` javascript

// 初始化RAL
RAL.init({
  confDir: path.join(process.cwd(), 'api/empty')
});

```

接着在代码里通过[Config.loadRawConf](https://github.com/fex-team/node-ral/blob/master/lib/config.js#L91)方法加载服务的配置对象
但是这个时候[lib/config.js#L232](https://github.com/fex-team/node-ral/blob/master/lib/config.js#L232)中的contextCache[serviceID] 为undefined
我想大概是因为缓存是在load方法中注册的吧

我想在这行代码前面加上下面的代码, 用来确保缓存缓存被正常初始化;
``` javascript

if (!contextCache[serviceID]) {
  contextCache[serviceID] = {};
}

```

可以提个pr吗？

**Comment by hefangshi** [comment]
可以，谢谢建议，近期也会完善ral的配置动态更新机制：）
