### ISSUE TITLE
httpProtocolBase 数据问题

### ISSUE THREAD

**Issue by qingxiao** [fex-team/node-ral#41]
0.11.x中有对 data处理的修改，当数据量比较多的时候，导致http请求服务获取数据不完整，
0.9.x版本是可以，
不清楚是什么问题导致的，麻烦能否看下
个人猜测240行， chunk如果是片段导致
···
ResponseStream.prototype.write = function(chunk) {
    // store the data
    this.chunks.push(chunk);
    this.emit('data', chunk);
};

···

**Comment by hefangshi** [comment]
这里的修改的确是会导致这样的问题，当时也考虑到了，所以专门测了一下数据量很大的接口没发现问题，同时已经用单测覆盖了这样的case。

不过听你描述的确是和这里有关，有HTTP请求服务的示例么？我实测看看

**Comment by hefangshi** [comment]
https://github.com/fex-team/node-ral/blob/master/test/protocol/http_protocol_post_test.js#L170-L176

这里使用了多次写数据流的方式，确认触发了chunk处理。

**Comment by qingxiao** [comment]
你把服务数据放到另一台电脑上，数据量搞大点，如果可以就限制下网速，
这个问题我自己电脑试了没问题，其他多个同事有遇到，由于数据是内部的，不方便给出，就是大概有几千个字符的json

node原生模块的httpRequest返回数据如果量大会分多次chunk的，把代码改成node-ral@0.9.x那样处理就好了

**Comment by hefangshi** [comment]
现在是每次data都存储了chunk数据，在end的时候一起发送出去的。并非没有处理chunk。

**Comment by qingxiao** [comment]
代码里面 
this.emit('data', chunk);
好像会去 unpack 数据，由于不是完整的json字符串导致报错

**Comment by hefangshi** [comment]
你是不是ral更新的有问题？以前是这样，现在是end后才unpack的，要不把ral的node_modules重新安装一下？

**Comment by qingxiao** [comment]
使用的 0.11.1版本~应该不会是node_modules问题，因为有几个同事都遇到了

**Comment by hefangshi** [comment]
可以看看

https://github.com/fex-team/node-ral/commit/e627faaaece56dc2f41d689976130eac1ffbb76e

里面的ral.js，unpack操作已经是end后触发的了

**Comment by hefangshi** [comment]
另外可以看看你们的json数据有多大么？

**Comment by qingxiao** [comment]
之前遇到一个 有4000多个字符，

**Comment by hefangshi** [comment]
修改了testcase，https://github.com/fex-team/node-ral/commit/85ed22f830014148d5546c80ae25bb3fd830ebac

增加了返回的数据量，每一小段都独立chunk输出，检查了末端数据，均没有发现问题

还增加了一个获取远程300kb脚本文件的testcase也没有发现问题

https://github.com/fex-team/node-ral/commit/405a0a37ec271e59cbf7c5ac5c4949c7565c0594

你能给出一个复现DEMO么？

**Comment by hefangshi** [comment]
这个问题目前发现是在unpack: stream下触发，目前0.12.1已经将unpack的stream修改回滚了。
