### ISSUE TITLE
这个框架的规划是什么

### ISSUE THREAD

**Issue by lawrence-peng** [fex-team/node-ral#55]
这个框架是不是要做成服务总线一样的框架，如Java世界的dubbo，还是如Uber tchannel一样，微服务的服务管理与服务治理框架？f

**Comment by hefangshi** [comment]
与dubbo这些相比，RAL会显的更加轻量化，它的确是一个服务治理框架，但是它的特征是更多的在客户端进行服务治理，而不是使用类似API Gateway的模式去治理，也就是一个重客户端的服务治理框架。外部开源版本中它的主要特性是对数据结构的封装以及服务管理功能。在我们内部使用中会和我们的服务Naming Service打通来实现更完善的服务管理能力比如后端配置如服务地址、机房调度、超时配置、请求协议等等的动态更新。

所以规划方面，RAL就是目前RAL长的样子：）
