### ISSUE TITLE
post请求

### ISSUE THREAD

**Issue by mewtwo-chi** [fex-team/node-ral#64]
用ral配置的post请求一直报403错，一直没找到问题，怀疑是配置有问题。可否给个请求post的配置

以下是我的配置：

module.exports.CNODEPOST= {           // 声明服务名为CNODEPOST
    // 请求协议与数据格式配置
    protocol: 'http',              // 使用http协议请求
    pack: 'form',                 // 数据封装为form
    unpack: 'json',               // 约定服务端返回JSON数据
    encoding: 'utf-8',             // 服务器返回utf-8编码
    balance: 'roundrobin',         // 负载均衡策略
    timeout: 500,                  // 请求最长超时时间500ms
    retry: 1,                      // 请求重试次数
    method: 'POST',                // 使用POST请求
    headers: {                     // 服务的全局headers
      'Content-Type':'application/x-www-form-urlencoded',
      'x-client-name': 'ral'
    },
    // 后端地址配置
    server: [                      // 可以配置多个后端地址
        {
            host: 'cnodejs.org',
            port: 80
        }
    ]
}

**Comment by hefangshi** [comment]
你可以给出一个可用的postman或者其他请求工具可以正常请求的例子，我可以协助看看应该如何配置。

**Comment by mewtwo-chi** [comment]
这个是postman的截图
[https://h5.9f.cn/stable/activity/project/app/3.0/fuyou/end/static/modules/i/postman_494ca7a.png](url)


以下是我的配置

调用服务CNODEPOST的接口：
module.exports.creatTopic = function(accesstoken,title,tab,content){ //新建主题

  return yog.ralP('CNODEPOST',{
    path:'/api/v1/topics',
    data:{
			accesstoken:accesstoken,      //String 用户的 accessToken
			title:title,                  //String 标题
			tab:tab,                      //String 目前有 ask share job
			content:content               //String 主体内容
		}
  })
  
};


服务配置：

module.exports.CNODEPOST= {           // 声明服务名为CNODEPOST
    protocol: 'http',              // 使用http协议请求
    pack: 'form',                 // 数据封装为form
    unpack: 'json',               // 约定服务端返回JSON数据
    encoding: 'utf-8',             // 服务器返回utf-8编码
    balance: 'roundrobin',         // 负载均衡策略
    timeout: 500,                  // 请求最长超时时间500ms
    retry: 1,                      // 请求重试次数
    method: 'POST',                // 使用POST请求
    headers: {                     // 服务的全局headers
      'x-client': 'ral'
    },
    server: [                      // 可以配置多个后端地址
        {
            host: 'cnodejs.org',
            port: 80
        }
    ]
}

**Comment by hefangshi** [comment]
form的确就是对应的 `application/x-www-form-urlencoded`

403错误是服务端forbidden，是否可能是accessToken问题？

**Comment by mewtwo-chi** [comment]
我用request插件发送post请求，虽然也是403，但是response里有很多数据。
但是用ral发送的话，返回值里只有这个两个字段：

{
  "statusCode": 403,
  "_hasReqInfo": true
}

这是ral对error有做处理吗，还是我需要配置什么才能得到完全的返回值？

**Comment by hefangshi** [comment]
https://github.com/fex-team/node-ral/wiki/%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE#includeextras

**Comment by hefangshi** [comment]
http2没有特殊支持，可以支持https接口的请求
